import server

gs = server.GameStore()
p1 = server.Player("aaa", "bbb", "ccc")
p2 = server.Player("zzz", "yyy", "xxx")
p3 = server.Player("a", "a", "a")
p4 = server.Player("b", "b", "b")
g1 = server.Game(p1.name,p2.name)
g2 = server.Game(p3.name,p4.name)
gs.players.addPlayer(p1)
gs.players.addPlayer(p2)
gs.players.addPlayer(p3)
gs.players.addPlayer(p4)
gs.games.addGame(g1)
print "adding game started on " + g1.lastTurnOn.strftime("%m-%d %H:%M")
gs.games.addGame(g2)
print "adding game started on " + g2.lastTurnOn.strftime("%m-%d %H:%M")
gs.save("sample_db.dat")
